# Generated by Django 5.0.1 on 2024-01-04 01:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('supplier', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Supplier Name')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('model', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Model')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU')),
                ('link', models.URLField(max_length=500, verbose_name='URL Product')),
                ('image', models.URLField(max_length=500, verbose_name='URL Image')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('enabled', models.BooleanField(default=True, help_text='Default: True', verbose_name='Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('shortname', models.CharField(max_length=100, verbose_name='Short Name')),
                ('base_url', models.URLField(verbose_name='Base URL')),
                ('image', models.URLField(blank=True, verbose_name='Image URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Current Price')),
                ('last_price', models.FloatField(verbose_name='Last Price')),
                ('discount_rate', models.FloatField(blank=True, null=True, verbose_name='Discount Rate')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.store'),
        ),
    ]
